# Generated by Django 3.1.1 on 2020-12-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='govJobs1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price1', models.CharField(max_length=100)),
                ('price2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='privateJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price1', models.CharField(max_length=100)),
                ('price2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='privateJobs1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price1', models.CharField(max_length=100)),
                ('price2', models.CharField(max_length=100)),
            ],
        ),
    ]
