# Generated by Django 3.1.1 on 2020-12-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='govjobs1',
            name='link',
            field=models.URLField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='privatejobs',
            name='link',
            field=models.URLField(max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='privatejobs1',
            name='link',
            field=models.URLField(max_length=225, null=True),
        ),
    ]
